name: Verify

permissions:
  contents: read

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.work
            go.work.sum
            go.sum
            ginx/go.sum
            fiberx/go.sum
            echox/go.sum
            hertzx/go.sum
            conformance/go.sum
      - name: Verify
        env:
          GOWORK: ${{ github.workspace }}/go.work
        run: make verify
